body:
- attributes:
    value: 'What not to report:

      - Bugs in custom builds or anything not downloaded from [here](https://github.com/Mika-Releases)

      - Missing Builds

      - PlayIntegrity not passing

      - Feature requests


      Make sure not to use extra mods when reporting a problem (for example: Magisk)

      '
  type: markdown
- attributes:
    label: Build Date
    description: 'The build date of the build currently running on your device
      (Settings -> Abount Phone -> LineageOS version).

      Example: `23.2-20260506-UNOFFICIAL-vince`'
  type: input
  validations:
    required: true
- attributes:
    label: Device
    multiple: false
    options:
    - Select one
    - Vince
    - ysl
    - tiffany
    - mido
    - spes/n
    - rosy
    - markw
    - MiThoriumSSI
    - mi8953
    - kenzo
    - certus
    - gale
  type: dropdown
  validations:
    required: true
- attributes:
    label: LineageOS Version
    multiple: false
    options:
    - Select one
    - lineage-23.2
    - lineage-22.2
    - lineage-21.0
    - lineage-20.0
  type: dropdown
  validations:
    required: true
- attributes:
    label: Describe the Bug
    description: A clear and concise description of what the bug is.
  type: textarea
  validations:
    required: true
- attributes:
    label: Steps to Reproduce
    description: Steps to reproduce the behavior, please provide a clear description
      of how to reproduce the issue, based on the linked minimal reproduction. Screenshots
      can be provided in the issue body below. If using code blocks, make sure that
      [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting)
      and double check that the rendered preview is not broken.
    value: |
      1.
      2.
      3.
  type: textarea
  validations:
    required: true
- attributes:
    description: A clear and concise description of what you expected to happen.
    label: Expected Behavior
  type: textarea
  validations:
    required: true
- attributes:
    description: Not obligatory, but suggest a fix/reason for the bug
    label: Possible Solution
  type: textarea
  validations:
    required: false
- attributes:
    value: Before posting the issue go through the steps you've written down to make
      sure the steps provided are detailed and clear.
  type: markdown
description: Create a bug report
name: Bug Report
